<a href="https://colab.research.google.com/github/NamNT36/Artifical-Intelligence/blob/main/AI_W8_FRI_24_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### ANN (Artifiicial Neural Network)
# Các Input Layer sử dụng các trọng số (Weight) truyền tín hiệu đến Output Layer

In [2]:
from sklearn.linear_model import Perceptron

x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]

model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [3]:
x1 = [[-0.5,-0.5],[10,-2],[-1,0.8],[3,5],[1,0.2],[-0.1,0.5],[0.5,0],[0.6,0],[0.7,0]]
y1 = model.predict(x1)
print(y1)
model.score(x1,y1)

[0 1 0 1 1 0 0 1 1]


1.0

In [4]:
# Iris: 4 tín hiệu vào (chiều dài, chiều rộng cánh hoa; chiều dài, chiều rộng nhị hoa)
# 1 tín hiệu ra (là 1 trong 3 loại hoa lan) (sử dụng One hot encoding -> 3bit)
# 0->Setosa
# 1->Versicolor
# 2->Virginica

In [5]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split  
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler  #Chuẩn hóa dữ liệu

iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[100:110])
print(y[100:110])
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3)  #test=30% -> train=70%
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]]
[2 2 2 2 2 2 2 2 2 2]


In [6]:
model = Perceptron(max_iter=40,eta0=0.1,random_state=0) #max_iter: số lần học, eta0: tốc độ học (0->1), random_state: lấy ngẫu nhiên dữ liệu
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ',accuracy_score(y_test,y_pred)) #Độ chính xác của test
#Độ chính xác của học cao hơn độ chính xác của test

[2 0 2 2 2 2 2 0 0 2 1 1 2 2 2 0 1 1 0 0 1 0 0 1 0 0 0 2 2 1 1 2 0 2 2 2 0
 0 2 1 1 0 2 0 2]
[2 0 2 2 2 2 1 0 0 1 1 1 2 2 2 0 1 1 0 0 2 0 0 1 1 0 0 2 2 2 1 2 0 2 2 2 1
 0 2 1 1 1 2 0 2]
Độ chính xác của mô hình:  0.8444444444444444


In [8]:
# Load library
import pandas as pd 
import numpy as np

# Create URL 
url = 'crabs.csv'

# Load data
data = pd.read_csv(url)

data.head()

correlation = data.corr()
print(correlation)

              index  fontallip  rearwidth    length     width     depth
index      1.000000   0.862876   0.840040  0.911436  0.928248  0.864459
fontallip  0.862876   1.000000   0.906988  0.978842  0.964956  0.987627
rearwidth  0.840040   0.906988   1.000000  0.892743  0.900402  0.889205
length     0.911436   0.978842   0.892743  1.000000  0.995023  0.983204
width      0.928248   0.964956   0.900402  0.995023  1.000000  0.967812
depth      0.864459   0.987627   0.889205  0.983204  0.967812  1.000000


In [9]:
#Loài
data.speies = data.speies.apply(lambda x: x.replace("O", "1"))
data.speies = data.speies.apply(lambda x: x.replace("B", "0"))

#Giới tính
data.sex = data.sex.apply(lambda x: x.replace("M", "1"))
data.sex = data.sex.apply(lambda x: x.replace("F", "0"))

print(data)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [14]:
x = data.drop(['sex'], axis = 1).replace(['F','M','B','O'],[0,1,0,1])
print(x[:5])
print(x[:5])
y = data.drop(['speies','index','fontallip','rearwidth','length','width','depth'], axis =1).replace(['F','M','B','O'],[0,1,0,1])
print(X[:5])
print(y[:5])
### Có scale
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)  #test=30% -> train=70%
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter=10000,eta0=0.01,random_state=0) #max_iter: số lần học, eta0: tốc độ học (0->1), random_state: lấy ngẫu nhiên dữ liệu
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ',accuracy_score(y_test,y_pred))

  speies  index  fontallip  rearwidth  length  width  depth
0      0      1        8.1        6.7    16.1   19.0    7.0
1      0      2        8.8        7.7    18.1   20.8    7.4
2      0      3        9.2        7.8    19.0   22.4    7.7
3      0      4        9.6        7.9    20.1   23.1    8.2
4      0      5        9.8        8.0    20.3   23.0    8.2
  speies  index  fontallip  rearwidth  length  width  depth
0      0      1        8.1        6.7    16.1   19.0    7.0
1      0      2        8.8        7.7    18.1   20.8    7.4
2      0      3        9.2        7.8    19.0   22.4    7.7
3      0      4        9.6        7.9    20.1   23.1    8.2
4      0      5        9.8        8.0    20.3   23.0    8.2
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
  sex
0   1
1   1
2   1
3   1
4   1
['1' '0' '0' '1' '1' '0' '1' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '1'
 '0' '1' '0' '1' '1' '1' '1' '0' '0' '1' '1' '1' '1' '1' '0' '0' '0' '0'
 '

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [19]:
### Trường hợp không có scale (bỏ _std)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)  #test=30% -> train=70%
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)
model = Perceptron(max_iter=1000,eta0=0.2,random_state=0) #max_iter: số lần học, eta0: tốc độ học (0->1), random_state: lấy ngẫu nhiên dữ liệu
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ',accuracy_score(y_test,y_pred))

['1' '0' '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '1' '0' '1' '1' '1'
 '1' '1' '0' '0' '1' '1' '1' '1' '0' '1' '0' '1' '1' '0' '1' '1' '0' '0'
 '1' '0' '1' '1' '0' '0' '1' '1' '1' '1' '0' '0' '0' '1' '1' '1' '0' '0'
 '1' '0' '1' '1' '0' '0']
    sex
20    1
91    0
168   0
199   0
77    0
179   0
138   1
87    0
36    1
60    0
106   1
108   1
178   0
1     1
183   0
133   1
26    1
53    0
43    1
48    1
166   0
165   0
144   1
19    1
107   1
143   1
193   0
50    0
94    0
5     1
2     1
155   0
136   1
30    1
169   0
174   0
59    0
172   0
110   1
13    1
58    0
95    0
23    1
120   1
38    1
101   1
167   0
56    0
164   0
130   1
127   1
116   1
71    0
182   0
24    1
88    0
124   1
7     1
97    0
92    0
Độ chính xác của mô hình:  0.95


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
